require:
  - rubocop-rspec

Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.8

Naming/MethodParameterName:
  MinNameLength: 2
  AllowNamesEndingInNumbers: true
  AllowedNames:
    - id
    - tx
    - to

Metrics/MethodLength:
  Max: 20
